# Generated by Django 4.2.7 on 2026-03-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='compartments/', verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خانة',
                'verbose_name_plural': 'الخانات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shelves/', verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='store.compartment', verbose_name='الخانة')),
            ],
            options={
                'verbose_name': 'رف',
                'verbose_name_plural': 'الرفوف',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة رئيسية')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر عند الطلب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر الطلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.shelf', verbose_name='الرف'),
        ),
    ]
