# Generated by Django 4.2.7 on 2026-03-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'الدفع عند الاستلام'), ('payment_gateway', 'بوابة الدفع الإلكتروني')], default='cash_on_delivery', max_length=30, verbose_name='طريقة الدفع'),
        ),
    ]
