# Generated by Django 4.2.7 on 2026-03-18 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_add_payment_and_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'تم الاسترجاع')], default='pending', max_length=20, verbose_name='حالة المرتجع')),
                ('reason', models.CharField(choices=[('defective', 'منتج معيب'), ('wrong_item', 'منتج خاطئ'), ('not_as_described', 'لا يطابق الوصف'), ('changed_mind', 'تغيير الرأي'), ('other', 'سبب آخر')], default='other', max_length=30, verbose_name='سبب الإرجاع')),
                ('reason_details', models.TextField(blank=True, verbose_name='تفاصيل السبب')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الاسترجاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='رمز فريد للمنتج (مثال: T-001). سيتم توليده تلقائياً إذا ترك فارغاً', max_length=50, null=True, unique=True, verbose_name='رمز المنتج'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'الدفع عند الاستلام'), ('payment_gateway', 'الدفع بالبطاقة (فيزا / مدى)')], default='cash_on_delivery', max_length=30, verbose_name='طريقة الدفع'),
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية المرتجعة')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر عند الشراء')),
                ('condition', models.CharField(blank=True, help_text='حالة المنتج عند الإرجاع', max_length=100, verbose_name='حالة المنتج')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='المنتج')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.return', verbose_name='طلب المرتجع')),
            ],
            options={
                'verbose_name': 'عنصر مرتجع',
                'verbose_name_plural': 'عناصر المرتجع',
            },
        ),
        migrations.AddField(
            model_name='return',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.order', verbose_name='الطلب الأصلي'),
        ),
        migrations.AddField(
            model_name='return',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
