# Generated by Django 4.2.7 on 2026-03-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_add_sku_and_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال'),
        ),
    ]
