# Generated by Django 4.2.7 on 2026-03-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_add_phone_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الجوال'),
        ),
    ]
