# Generated by Django 4.2.7 on 2026-03-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_make_phone_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('code', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('username', models.CharField(max_length=150, verbose_name='اسم المستخدم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('password_hash', models.CharField(max_length=300, verbose_name='كلمة المرور المشفرة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
            ],
            options={
                'verbose_name': 'رمز التحقق',
                'verbose_name_plural': 'رموز التحقق',
                'ordering': ['-created_at'],
            },
        ),
    ]
