# Generated by Django 4.2.7 on 2026-03-18 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_add_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة الإلغاء'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('customer_request', 'طلب العميل'), ('out_of_stock', 'نفاد المخزون'), ('payment_failed', 'فشل الدفع'), ('admin_decision', 'قرار إداري'), ('other', 'أخرى')], max_length=30, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('registered', 'مستخدم مسجل'), ('guest', 'ضيف')], default='registered', max_length=20, verbose_name='نوع العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('failed', 'فشل الدفع'), ('cancelled', 'دفع ملغي'), ('refunded', 'تم الاسترداد'), ('partially_refunded', 'استرداد جزئي')], default='pending', max_length=30, verbose_name='حالة الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='رمز التتبع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('processing', 'قيد التجهيز'), ('ready_to_ship', 'جاهز للشحن'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(max_length=30, verbose_name='الحالة الجديدة')),
                ('old_payment_status', models.CharField(blank=True, max_length=30, verbose_name='حالة الدفع السابقة')),
                ('new_payment_status', models.CharField(blank=True, max_length=30, verbose_name='حالة الدفع الجديدة')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='تلقائي')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_changes', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سجل حالة الطلب',
                'verbose_name_plural': 'سجلات حالات الطلبات',
                'ordering': ['created_at'],
            },
        ),
    ]
