# Generated by Django 4.2.7 on 2026-03-18 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_order_status_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='refund_status',
            field=models.CharField(choices=[('not_required', 'غير مطلوب'), ('pending', 'في انتظار الاسترداد'), ('completed', 'تم الاسترداد'), ('partial', 'استرداد جزئي')], default='pending', max_length=20, verbose_name='حالة الاسترداد'),
        ),
        migrations.AddField(
            model_name='return',
            name='stock_status',
            field=models.CharField(choices=[('pending', 'لم يُعَد للمخزون'), ('restocked', 'أُعيد للمخزون'), ('damaged', 'تالف — لن يُعاد')], default='pending', max_length=20, verbose_name='حالة المخزون'),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('requested', 'مقدَّم بانتظار المراجعة'), ('reviewing', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('received', 'تم استلام المنتج'), ('completed', 'مكتمل — تم الاسترداد')], default='requested', max_length=20, verbose_name='حالة المرتجع'),
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(max_length=30, verbose_name='الحالة الجديدة')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='تلقائي')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_changes', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.return', verbose_name='طلب المرتجع')),
            ],
            options={
                'verbose_name': 'سجل حالة المرتجع',
                'verbose_name_plural': 'سجلات حالات المرتجعات',
                'ordering': ['created_at'],
            },
        ),
    ]
