# Generated by Django 4.2.7 on 2026-03-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_return_engine_phase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fake_shipping', 'شركة شحن وهمية')], default='fake_shipping', max_length=30, verbose_name='شركة الشحن')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم التتبع')),
                ('status', models.CharField(choices=[('created', 'تم إنشاء الشحنة'), ('picked_up', 'تم الاستلام من المتجر'), ('in_transit', 'بالطريق'), ('out_for_delivery', 'خرجت للتسليم'), ('delivered', 'تم التسليم'), ('failed', 'تعثر التسليم')], default='created', max_length=30, verbose_name='حالة الشحنة')),
                ('last_event', models.TextField(blank=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='store.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fake_gateway', 'بوابة دفع وهمية')], default='fake_gateway', max_length=30, verbose_name='المزود')),
                ('status', models.CharField(choices=[('created', 'تم الإنشاء'), ('pending', 'معلق'), ('success', 'نجح'), ('failed', 'فشل')], default='created', max_length=20, verbose_name='الحالة')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='مرجع العملية')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='بيانات خام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='store.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'محاولة دفع',
                'verbose_name_plural': 'محاولات الدفع',
                'ordering': ['-created_at'],
            },
        ),
    ]
