# Generated by Django 4.2.7 on 2026-03-18 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_fake_payment_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المندوب'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('regular', 'مستخدم عادي'), ('courier', 'مندوب شحن')], default='regular', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
