# Generated by Django 4.2.7 on 2026-03-18 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_courier_and_shipment_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_orders', to=settings.AUTH_USER_MODEL, verbose_name='مجهّز الطلب'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('regular', 'مستخدم عادي'), ('courier', 'مندوب شحن'), ('packer', 'موظف تجهيز الطلبات')], default='regular', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
