# Generated by Django 4.2.7 on 2026-03-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_warehouse_packer_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='كود البوليصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_code', to='store.order', verbose_name='الطلب')),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_code', to='store.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'كود بوليصة',
                'verbose_name_plural': 'أكواد البوالص',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='رمز التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم استخدامه')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_otps', to='store.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'رمز تسليم',
                'verbose_name_plural': 'رموز التسليم',
            },
        ),
    ]
