# Generated by Django 4.2.7 on 2026-03-22 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_userprofile_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(help_text='رقم البوليصة الظاهر على وثيقة الشحن أو من شركة الناقل.', max_length=64, verbose_name='رقم البوليصة')),
                ('barcode_value', models.CharField(blank=True, help_text='النص الذي يقرأه الماسح الضوئي أو المرجع الداخلي للباركود.', max_length=512, verbose_name='قيمة الباركود (أرشيف آمن)')),
                ('linked_internal_code', models.CharField(blank=True, help_text='مرجع لكود الطباعة على الملصق (مثل كود QR الداخلي).', max_length=32, verbose_name='الكود الداخلي للملصق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات المستودع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_waybills_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_waybill', to='store.order', verbose_name='الطلب')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='store.shipment', verbose_name='الشحنة المرتبطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_waybills_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'بوليصة شحن',
                'verbose_name_plural': 'بوالص الشحن',
            },
        ),
    ]
