# Generated by Django 4.2.7 on 2026-03-23 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_shipping_waybill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageSeenMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, verbose_name='المفتاح')),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الاطلاع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manage_seen_markers', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'اطلاع مسؤول',
                'verbose_name_plural': 'اطلاعات المسؤولين',
            },
        ),
        migrations.AddConstraint(
            model_name='manageseenmarker',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_manage_seen_user_key'),
        ),
    ]
