# Generated by Django 4.2.7 on 2026-03-23 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_manage_seen_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رمز المشاركة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='مرات الفتح')),
                ('applied_count', models.PositiveIntegerField(default=0, verbose_name='مرات التطبيق')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر فتح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_shares', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مشاركة سلة',
                'verbose_name_plural': 'مشاركات السلة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=255, null=True, verbose_name='معرّف الرابط'),
        ),
        migrations.CreateModel(
            name='CartShareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر وقت الإنشاء')),
                ('cart_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cartshare', verbose_name='مشاركة السلة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_share_items', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر مشاركة سلة',
                'verbose_name_plural': 'عناصر مشاركة السلة',
            },
        ),
        migrations.AddConstraint(
            model_name='cartshareitem',
            constraint=models.UniqueConstraint(fields=('cart_share', 'product'), name='unique_cartshare_product'),
        ),
    ]
