# Generated by Django 4.2.7 on 2026-03-23 07:10

from django.db import migrations, models
from django.utils.text import slugify


def populate_product_slugs(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    for p in Product.objects.all().order_by('id'):
        if p.slug:
            continue
        base_name = p.name_ar or p.name_en or p.sku or 'product'
        base_slug = slugify(base_name) or 'product'
        candidate = base_slug
        idx = 2
        while Product.objects.filter(slug=candidate).exclude(pk=p.pk).exists():
            candidate = f'{base_slug}-{idx}'
            idx += 1
        p.slug = candidate
        p.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_cartshare_product_slug_cartshareitem_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_product_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='معرّف الرابط'),
        ),
    ]
