# Generated by Django 4.2.7 on 2026-03-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0022_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث لحالة التوفر'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_updates', to=settings.AUTH_USER_MODEL, verbose_name='محدّث حالة التوفر'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='تُطبق على مندوب الشحن وموظف التجهيز فقط.', verbose_name='متوفر لاستقبال المهام الجديدة'),
        ),
    ]
