# Generated by Django 4.2.7 on 2026-03-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0023_userprofile_availability_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, verbose_name='رمز النسخة (SKU فرعي)')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='اسم النسخة')),
                ('color_name', models.CharField(blank=True, max_length=80, verbose_name='اللون')),
                ('color_hex', models.CharField(blank=True, help_text='#RRGGBB', max_length=7, verbose_name='لون HEX')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر النسخة')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='مخزون النسخة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة للبيع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'نسخة منتج',
                'verbose_name_plural': 'نسخ المنتجات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('inbound', 'إضافة مخزون'), ('sale', 'بيع/خصم'), ('cancel_restore', 'استرجاع بعد إلغاء'), ('return_restore', 'استرجاع بعد مرتجع'), ('adjustment', 'تعديل يدوي')], max_length=30, verbose_name='نوع الحركة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('reference_type', models.CharField(blank=True, max_length=30, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المرجع')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='store.productvariant', verbose_name='نسخة المنتج')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cartshareitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_share_items', to='store.productvariant', verbose_name='نسخة المنتج'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.productvariant', verbose_name='نسخة المنتج'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='store.productvariant', verbose_name='نسخة المنتج'),
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/variants/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='نص بديل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة أساسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productvariant', verbose_name='نسخة المنتج')),
            ],
            options={
                'verbose_name': 'صورة نسخة المنتج',
                'verbose_name_plural': 'صور نسخ المنتجات',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['variant', 'sort_order'], name='store_produ_variant_e6f15c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active', 'sort_order'], name='store_produ_product_9e89aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_variant_code_per_product'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['variant', 'created_at'], name='store_inven_variant_cf7876_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='store_inven_referen_0c0171_idx'),
        ),
    ]
