# Generated by Cursor on 2026-03-24
from django.db import migrations


def seed_default_variants(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    ProductVariant = apps.get_model('store', 'ProductVariant')
    OrderItem = apps.get_model('store', 'OrderItem')
    ReturnItem = apps.get_model('store', 'ReturnItem')
    CartShareItem = apps.get_model('store', 'CartShareItem')

    product_to_variant_id = {}

    for product in Product.objects.all().only('id', 'sku', 'price', 'stock'):
        existing = ProductVariant.objects.filter(product_id=product.id).order_by('sort_order', 'id').first()
        if existing:
            variant = existing
        else:
            base_code = (product.sku or f"P{product.id}").strip() or f"P{product.id}"
            candidate = f"{base_code}-DEFAULT"
            idx = 2
            while ProductVariant.objects.filter(product_id=product.id, code=candidate).exists():
                candidate = f"{base_code}-DEFAULT-{idx}"
                idx += 1

            variant = ProductVariant.objects.create(
                product_id=product.id,
                code=candidate,
                title='النسخة الافتراضية',
                stock_quantity=product.stock or 0,
                price=product.price,
                sort_order=0,
                is_active=True,
            )
        product_to_variant_id[product.id] = variant.id

    for item in OrderItem.objects.filter(variant_id__isnull=True).only('id', 'product_id'):
        vid = product_to_variant_id.get(item.product_id)
        if vid:
            OrderItem.objects.filter(pk=item.pk).update(variant_id=vid)

    for item in ReturnItem.objects.filter(variant_id__isnull=True).only('id', 'product_id'):
        vid = product_to_variant_id.get(item.product_id)
        if vid:
            ReturnItem.objects.filter(pk=item.pk).update(variant_id=vid)

    for item in CartShareItem.objects.filter(variant_id__isnull=True).only('id', 'product_id'):
        vid = product_to_variant_id.get(item.product_id)
        if vid:
            CartShareItem.objects.filter(pk=item.pk).update(variant_id=vid)


def noop_reverse(apps, schema_editor):
    # لا نحذف البيانات المزروعة لتجنب فقد روابط العناصر التاريخية.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_productvariant_inventorymovement_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_variants, noop_reverse),
    ]
