# Generated by Django 4.2.7 on 2026-03-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_seed_default_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='نص بديل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية للمنتج')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة معرض المنتج',
                'verbose_name_plural': 'صور معرض المنتجات',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['product', 'sort_order'], name='store_produ_product_b257b7_idx')],
            },
        ),
    ]
