# Generated by Django 4.2.7 on 2026-03-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_variant_images_to_single_and_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_gallery_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productgalleryimage', verbose_name='صورة المنتج المختارة'),
        ),
    ]
