# Generated by Django 4.2.7 on 2026-03-24 11:38

from django.db import migrations, models


def seed_gallery_meta(apps, schema_editor):
    ProductGalleryImage = apps.get_model('store', 'ProductGalleryImage')
    Product = apps.get_model('store', 'Product')
    by_product = {}
    for img in ProductGalleryImage.objects.all().order_by('product_id', 'sort_order', 'id'):
        pid = img.product_id
        if pid not in by_product:
            by_product[pid] = 0
        by_product[pid] += 1
        product = Product.objects.filter(pk=pid).only('sku', 'name_ar', 'price', 'stock').first()
        base = ((product.sku if product else '') or f"P{pid}").strip() or f"P{pid}"
        img.code = f"{base}-G{by_product[pid]:03d}"
        img.title = (product.name_ar if product else '') or ''
        img.price = product.price if product else None
        img.stock_quantity = int(product.stock or 0) if product else 0
        img.save(update_fields=['code', 'title', 'price', 'stock_quantity'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_orderitem_selected_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgalleryimage',
            name='code',
            field=models.CharField(blank=True, max_length=90, verbose_name='SKU صورة المنتج'),
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الصورة'),
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية الصورة'),
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=140, verbose_name='اسم الصورة'),
        ),
        migrations.RunPython(seed_gallery_meta, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productgalleryimage',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_gallery_code_per_product'),
        ),
    ]
