# Generated by Django 4.2.7 on 2026-03-25 05:13

from django.db import migrations, models
import django.db.models.deletion


def backfill_order_return_snapshots(apps, schema_editor):
    OrderItem = apps.get_model('store', 'OrderItem')
    ReturnItem = apps.get_model('store', 'ReturnItem')
    ProductVariantImage = apps.get_model('store', 'ProductVariantImage')
    ProductGalleryImage = apps.get_model('store', 'ProductGalleryImage')

    for oi in OrderItem.objects.select_related('product', 'variant', 'selected_gallery_image').iterator(chunk_size=100):
        if not oi.product_id:
            continue
        p = oi.product
        name_ar = (getattr(p, 'name_ar', '') or '').strip()
        vlabel = ''
        sku = ''
        img_url = ''
        if oi.variant_id and oi.variant:
            v = oi.variant
            vlabel = ((getattr(v, 'color_name', None) or '') or (getattr(v, 'title', None) or '')).strip()
            sku = (getattr(v, 'code', None) or '').strip()
        elif oi.selected_gallery_image_id and oi.selected_gallery_image:
            g = oi.selected_gallery_image
            vlabel = (getattr(g, 'title', None) or '').strip()
            sku = (getattr(g, 'code', None) or '').strip()
        else:
            sku = (getattr(p, 'sku', None) or '').strip()

        if oi.variant_id:
            pvi = (
                ProductVariantImage.objects.filter(variant_id=oi.variant_id)
                .order_by('-is_primary', 'sort_order', 'id')
                .first()
            )
            if pvi and getattr(pvi, 'image', None):
                try:
                    img_url = pvi.image.url
                except ValueError:
                    img_url = ''
        elif oi.selected_gallery_image_id and oi.selected_gallery_image:
            g = oi.selected_gallery_image
            if getattr(g, 'image', None):
                try:
                    img_url = g.image.url
                except ValueError:
                    img_url = ''
        else:
            g2 = (
                ProductGalleryImage.objects.filter(product_id=oi.product_id)
                .order_by('-is_primary', 'sort_order', 'id')
                .first()
            )
            if g2 and getattr(g2, 'image', None):
                try:
                    img_url = g2.image.url
                except ValueError:
                    img_url = ''
            elif getattr(p, 'image', None):
                try:
                    img_url = p.image.url
                except ValueError:
                    img_url = ''

        OrderItem.objects.filter(pk=oi.pk).update(
            product_name_snapshot=name_ar,
            variant_label_snapshot=vlabel[:200],
            line_sku_snapshot=sku[:120],
            image_url_snapshot=(img_url or '')[:500],
        )

    for ri in ReturnItem.objects.select_related('product', 'variant').iterator(chunk_size=100):
        if not ri.product_id:
            continue
        p = ri.product
        pname = (getattr(p, 'name_ar', '') or '').strip()
        psku = (getattr(p, 'sku', None) or '').strip()
        vlabel = ''
        if ri.variant_id and ri.variant:
            v = ri.variant
            vlabel = ((getattr(v, 'color_name', None) or '') or (getattr(v, 'title', None) or '')).strip()
        ReturnItem.objects.filter(pk=ri.pk).update(
            product_name_snapshot=pname[:250],
            product_sku_snapshot=psku[:120],
            variant_label_snapshot=vlabel[:200],
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_productgalleryimage_code_productgalleryimage_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url_snapshot',
            field=models.CharField(blank=True, max_length=500, verbose_name='رابط صورة السطر عند الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_sku_snapshot',
            field=models.CharField(blank=True, max_length=120, verbose_name='SKU السطر عند الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, help_text='يُستخدم لعرض الطلب بعد حذف المنتج من الكتالوج', max_length=250, verbose_name='اسم المنتج عند الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_label_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='وصف اللون/النسخة عند الطلب'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=250, verbose_name='اسم المنتج عند المرتجع'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product_sku_snapshot',
            field=models.CharField(blank=True, max_length=120, verbose_name='SKU المنتج عند المرتجع'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='variant_label_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='وصف النسخة عند المرتجع'),
        ),
        migrations.RunPython(backfill_order_return_snapshots, noop_reverse),
        migrations.AlterField(
            model_name='cartshareitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_share_items', to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='cartshareitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_share_items', to='store.productvariant', verbose_name='نسخة المنتج'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productvariant', verbose_name='نسخة المنتج'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='store.productvariant', verbose_name='نسخة المنتج'),
        ),
    ]
