# Generated by Django 4.2.7 on 2026-03-25 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0030_orderitem_snapshots_set_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='كود الكوبون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('discount_type', models.CharField(choices=[('percent', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('max_uses_total', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'كوبونات',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العرض')),
                ('description', models.TextField(blank=True, verbose_name='وصف العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('discount_type', models.CharField(choices=[('percent', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للكمية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='product_promotions', to='store.product', verbose_name='المنتجات')),
                ('variants', models.ManyToManyField(blank=True, related_name='variant_promotions', to='store.productvariant', verbose_name='النسخ')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال (للكوبون)')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='store.coupon', verbose_name='الكوبون')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تسجيل استخدام الكوبون',
                'verbose_name_plural': 'سجلات استخدام الكوبونات',
                'ordering': ['-redeemed_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'user'), name='unique_coupon_per_user'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'guest_phone'), name='unique_coupon_per_guest_phone'),
        ),
    ]
