# Generated by Django 4.2.7 on 2026-03-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_coupon_promotion_couponredemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_promotions', to='store.category', verbose_name='الأصناف'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='compartments',
            field=models.ManyToManyField(blank=True, related_name='compartment_promotions', to='store.compartment', verbose_name='الخانات'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='scope',
            field=models.CharField(choices=[('all', 'الكل'), ('compartments', 'الخانات'), ('shelves', 'الرفوف'), ('categories', 'الأصناف'), ('products', 'المنتجات'), ('variants', 'النسخ')], default='all', help_text='اختر أين سيتم تطبيق الخصم (خانة/رف/صنف/منتج/نسخة/الكل).', max_length=30, verbose_name='نطاق التطبيق'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='shelves',
            field=models.ManyToManyField(blank=True, related_name='shelf_promotions', to='store.shelf', verbose_name='الرفوف'),
        ),
    ]
