# Generated by GPT assistant on 2026-03-25

from django.db import migrations


def backfill_promotion_scope(apps, schema_editor):
    Promotion = apps.get_model("store", "Promotion")
    # Backfill only when scope is default/empty to keep any future edits safe.
    for promo in Promotion.objects.all().iterator():
        scope = (getattr(promo, "scope", None) or "all").strip() or "all"
        if scope != "all":
            continue

        # If any variants selected → treat as variants-level scope.
        try:
            if promo.variants.exists():
                promo.scope = "variants"
                promo.save(update_fields=["scope"])
                continue
        except Exception:
            pass

        # If any products selected → treat as products-level scope.
        try:
            if promo.products.exists():
                promo.scope = "products"
                promo.save(update_fields=["scope"])
                continue
        except Exception:
            pass

        # Otherwise keep "all".


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0032_promotion_categories_promotion_compartments_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_promotion_scope, migrations.RunPython.noop),
    ]

