# Generated by GPT assistant on 2026-03-25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0033_promotion_scope_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="applied_promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="store.promotion",
                verbose_name="العرض المطبق",
            ),
        ),
    ]

