# Generated by Django 4.2.7 on 2026-03-30 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0034_orderitem_applied_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('regular', 'مستخدم عادي'), ('courier', 'مندوب شحن'), ('packer', 'موظف تجهيز الطلبات'), ('customer_service', 'موظف خدمة العملاء')], default='regular', max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الجوال (للضيف)')),
                ('status', models.CharField(choices=[('waiting_for_staff', 'بانتظار ممثل خدمة العملاء'), ('active', 'نشطة'), ('ended', 'منتهية')], db_index=True, default='waiting_for_staff', max_length=40, verbose_name='حالة المحادثة')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنهاء')),
                ('ended_by_type', models.CharField(blank=True, default='', help_text='customer|staff|system', max_length=20, verbose_name='من أنهى')),
                ('last_customer_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخر رسالة من العميل')),
                ('last_staff_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخر رسالة من الموظف')),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التنبيه')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='مؤرشف')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الأرشفة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_threads', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المكلف')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_threads', to=settings.AUTH_USER_MODEL, verbose_name='العميل (مسجل)')),
            ],
            options={
                'verbose_name': 'محادثة خدمة العملاء',
                'verbose_name_plural': 'محادثات خدمة العملاء',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'عميل'), ('staff', 'موظف'), ('system', 'نظام')], default='customer', max_length=20, verbose_name='المرسل')),
                ('text', models.TextField(verbose_name='النص')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.supportthread', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة خدمة العملاء',
                'verbose_name_plural': 'رسائل خدمة العملاء',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['status', 'is_archived'], name='store_suppo_status_20488f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'created_at'], name='store_suppo_thread__191250_idx'),
        ),
    ]
