# Generated by Django 4.2.7 on 2026-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_userprofile_account_type_supportthread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('regular', 'مستخدم عادي'), ('courier', 'مندوب شحن'), ('packer', 'موظف تجهيز الطلبات'), ('customer_service', 'موظف خدمة العملاء'), ('warehouse_manager', 'مسؤول المستودع'), ('shipping_manager', 'مسؤول الشحن')], default='regular', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
