# Generated by Django 4.2.7 on 2026-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_add_warehouse_shipping_manager_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(
                choices=[
                    ('regular', 'مستخدم عادي'),
                    ('courier', 'مندوب شحن'),
                    ('packer', 'موظف تجهيز الطلبات'),
                    ('customer_service', 'موظف خدمة العملاء'),
                    ('customer_service_manager', 'مسؤول خدمة العملاء'),
                    ('warehouse_manager', 'مسؤول المستودع'),
                    ('shipping_manager', 'مسؤول الشحن'),
                ],
                default='regular',
                max_length=30,
                verbose_name='نوع الحساب',
            ),
        ),
    ]
