# Generated by Django 4.2.7 on 2026-04-21 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_customer_service_manager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalSupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('shipping', 'الشحن'), ('warehouse', 'المستودع')], db_index=True, max_length=20, verbose_name='القسم')),
                ('status', models.CharField(choices=[('waiting_manager', 'بانتظار مسؤول القسم'), ('active', 'نشطة'), ('closed', 'مغلقة')], db_index=True, default='waiting_manager', max_length=30, verbose_name='الحالة')),
                ('last_staff_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخر رسالة موظف')),
                ('last_manager_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخر رسالة مسؤول')),
                ('waiting_notice_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال رسالة الانتظار')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_support_threads_as_manager', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_support_threads_as_staff', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'محادثة داخلية',
                'verbose_name_plural': 'المحادثات الداخلية',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['department', 'status'], name='store_inter_departm_fcc450_idx'), models.Index(fields=['staff_user', 'status'], name='store_inter_staff_u_6ef86f_idx'), models.Index(fields=['manager_user', 'status'], name='store_inter_manager_22812e_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternalSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('staff', 'الموظف'), ('manager', 'المسؤول'), ('system', 'النظام')], default='staff', max_length=20, verbose_name='المرسل')),
                ('text', models.TextField(blank=True, verbose_name='النص')),
                ('image', models.ImageField(blank=True, null=True, upload_to='internal_support/', verbose_name='صورة مرفقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_support_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.internalsupportthread', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة داخلية',
                'verbose_name_plural': 'الرسائل الداخلية',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='store_inter_thread__ce8ed7_idx')],
            },
        ),
    ]
