# Generated by Django 4.2.7 on 2026-04-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_internal_support_chat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internalsupportmessage',
            new_name='store_inter_thread__25643d_idx',
            old_name='store_inter_thread__ce8ed7_idx',
        ),
        migrations.RenameIndex(
            model_name='internalsupportthread',
            new_name='store_inter_departm_dcd775_idx',
            old_name='store_inter_departm_fcc450_idx',
        ),
        migrations.RenameIndex(
            model_name='internalsupportthread',
            new_name='store_inter_staff_u_24dc46_idx',
            old_name='store_inter_staff_u_6ef86f_idx',
        ),
        migrations.RenameIndex(
            model_name='internalsupportthread',
            new_name='store_inter_manager_7c8699_idx',
            old_name='store_inter_manager_22812e_idx',
        ),
    ]
